from dotenv import load_dotenv

import os


load_dotenv()


OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
OPENAI_API_CHAT_ENDPOINT = os.getenv("OPENAI_API_CHAT_ENDPOINT")
OPENAI_API_SPEECH_ENDPOINT = os.getenv("OPENAI_API_SPEECH_ENDPOINT")
OPENAI_API_TRANSCRIPTION_ENDPOINT = os.getenv("OPENAI_API_TRANSCRIPTION_ENDPOINT")
OPENAI_API_BASE = os.getenv("OPENAI_API_BASE")
HF_TOKEN = os.getenv("HF_TOKEN")
HF_HOME  = os.getenv("HF_HOME")
SD_TOKEN = os.getenv("SD_TOKEN")